/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'name' : string,
  'foodItemId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export interface FoodItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'deliveryBoyId' : [] | [Principal],
  'totalAmount' : bigint,
  'customerId' : Principal,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export type Role = { 'deliveryBoy' : null } |
  { 'customer' : null } |
  { 'owner' : null };
export interface User { 'id' : Principal, 'name' : string, 'role' : Role }
export interface UserProfile { 'name' : string, 'role' : Role }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOrder' : ActorMethod<[bigint, Principal], undefined>,
  'addFoodItem' : ActorMethod<[string, string, bigint, string], bigint>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAssignedOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCurrentUser' : ActorMethod<[], User>,
  'getDeliveryBoys' : ActorMethod<[], Array<User>>,
  'getMenu' : ActorMethod<[], Array<FoodItem>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getTotalOrders' : ActorMethod<[], bigint>,
  'getTotalRevenue' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginAs' : ActorMethod<[string, Role], Principal>,
  'placeOrder' : ActorMethod<[], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFoodItem' : ActorMethod<
    [bigint, string, string, bigint, string, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
